# Generated by Django 3.2.16 on 2022-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221203_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='mark',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
