# Generated by Django 3.2.16 on 2022-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rating_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='mark',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=2, null=True),
        ),
    ]
