# Generated by Django 3.2.16 on 2022-12-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_rating_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='mark',
            field=models.IntegerField(null=True, verbose_name=(('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))),
        ),
    ]
